# Generated by Django 4.0.6 on 2022-08-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empl', '0002_employee_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Departement',
            field=models.CharField(choices=[('CL', 'Cloud'), ('DV', 'Devops'), ('RS', 'Réseau'), ('SC', 'Securité'), ('HR', 'HR'), ('FN', 'Finance'), ('OT', 'Other')], default='OT', max_length=2),
        ),
    ]
