# Generated by Django 4.0.6 on 2022-08-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empl', '0003_employee_departement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Departement',
            field=models.CharField(choices=[('Cloud', 'Cloud'), ('DevOps', 'Devops'), ('Réseau', 'Réseau'), ('Sécurité', 'Securité'), ('HR', 'HR'), ('Finance', 'Finance'), ('Autre', 'Other')], default='Autre', max_length=8),
        ),
    ]
