# Generated by Django 4.0.6 on 2022-08-02 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empl', '0004_alter_employee_departement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
