# Generated by Django 4.0.6 on 2022-08-03 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empl', '0005_alter_employee_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='salary',
        ),
    ]
