# Generated by Django 4.0.6 on 2022-08-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empl', '0006_remove_employee_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default='UDN77f3srZ', max_length=50),
        ),
    ]
