# Generated by Django 4.0.6 on 2022-08-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empl', '0007_employee_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(default='4S5GFELj7k', max_length=18),
        ),
    ]
